src/Entity/Event.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\Post;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\EventRepository;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\GetCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: EventRepository::class)]
#[ApiResource(
    operations: [
    new Get( normalizationContext: ['groups' => ['event:list']] ),
    new GetCollection( normalizationContext: ['groups' => ['event:item']] ),
    new Post(
        denormalizationContext: ['groups' => ['event:write']],
        validationContext: ['groups' => ['Default', 'create']]
    )
    ]
)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column] 
    #[Groups(['event:list', 'event:item'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]   
    #[Groups(['event:list', 'event:item', 'event:write'])]
    private ?string $title = null;

    #[ORM\Column]
    #[Groups(['event:list', 'event:item', 'event:write'])]
    #[Assert\NotBlank(groups: ['create'])]
    private ?\DateTimeImmutable $date = null;

    #[ORM\Column]
    #[Groups(['event:list', 'event:item', 'event:write'])]
    #[Assert\NotBlank(groups: ['create'])]
    private ?int $max_players = null;

    #[ORM\Column]
    #[Groups(['event:list', 'event:item', 'event:write'])]
    #[Assert\NotBlank(groups: ['create'])]
    private ?int $game_id = null;

    #[ORM\Column(length: 255)]
    #[Groups(['event:list', 'event:item', 'event:write'])]
    #[Assert\NotBlank(groups: ['create'])]
    private ?string $place = null;
    
    #[ORM\ManyToOne(inversedBy: 'events')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['event:list', 'event:item', 'event:write'])]
    #[Assert\NotBlank(groups: ['create'])]
    private ?User $organizer = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'events')]
    private Collection $participants;

    /**
     * @var Collection<int, Invitation>
     */
    #[ORM\OneToMany(targetEntity: Invitation::class, mappedBy: 'event')]
    private Collection $invitations;

    
    public function __construct()
    {
        $this->participants = new ArrayCollection();
        $this->invitations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDate(): ?\DateTimeImmutable
    {
        return $this->date;
    }

    public function setDate(\DateTimeImmutable $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function formattedDate(): string
    {
        return $this->date->format('d/m/Y à H:i');
    }

    public function getMaxPlayers(): ?int
    {
        return $this->max_players;
    }

    public function setMaxPlayers(int $max_players): static
    {
        $this->max_players = $max_players;

        return $this;
    }

    public function getOrganizer(): ?User
    {
        return $this->organizer;
    }

    public function setOrganizer(?User $organizer): static
    {
        $this->organizer = $organizer;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(User $participant): static
    {
        if (!$this->participants->contains($participant)) {
            $this->participants->add($participant);
        }

        return $this;
    }

    public function removeParticipant(User $participant): static
    {
        $this->participants->removeElement($participant);

        return $this;
    }

    public function getGameId(): ?int
    {
        return $this->game_id;
    }

    public function setGameId(int $game_id): static
    {
        $this->game_id = $game_id;

        return $this;
    }

    public function getPlace(): ?string
    {
        return $this->place;
    }

    public function setPlace(string $place): static
    {
        $this->place = $place;

        return $this;
    }

    /**
     * @return Collection<int, Invitation>
     */
    public function getInvitations(): Collection
    {
        return $this->invitations;
    }

    public function addInvitation(Invitation $invitation): static
    {
        if (!$this->invitations->contains($invitation)) {
            $this->invitations->add($invitation);
            $invitation->setEvent($this);
        }

        return $this;
    }

    public function removeInvitation(Invitation $invitation): static
    {
        if ($this->invitations->removeElement($invitation)) {
            // set the owning side to null (unless already changed)
            if ($invitation->getEvent() === $this) {
                $invitation->setEvent(null);
            }
        }

        return $this;
    }
}

src/Controller/GameController.php
<?php

namespace App\Controller;

use App\Service\BoardGameGeekApiService;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class GameController extends AbstractController
{

    private $boardGameGeekApiService;

    public function __construct(BoardGameGeekApiService $boardGameGeekApiService)
    {
        $this->boardGameGeekApiService = $boardGameGeekApiService;
    }

    // Show games list
    #[Route('/game', name: 'game_show')]
    public function index(): Response
    {

        $games = $this->boardGameGeekApiService->getGames();

        return $this->render('game/showGames.html.twig', [
            'controller_name' => 'GameController',
            'games' => $games
        ]);
    }

    // Show game details
    #[Route('/game/{id}', name: 'game_details')]
    public function show(string $id): Response
    {
        $game = $this->boardGameGeekApiService->getGameDetailsById($id);

        return $this->render('game/details.html.twig', [
            'controller_name' => 'GameController',
            'game' => $game
        ]);
    }
}

templates/game/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail de {{game.name}}{% endblock %}

{% block body %}
<div class="flex justify-center min-h-dvh w-full md:p-20">
    <div class="flex flex-col h-max md:w-3/5  rounded-lg  shadow-card p-4">
        <div class="w-full h-80 rounded-lg overflow-hidden">
            <img class="w-full h-80 object-cover" src="{{game.thumbnail}}" alt="{{game.name}}">
        </div>
        <div class="flex flex-col gap-3 p-4 w-full">
            <h1>{{game.name}}</h1>
            <p>{{game.description|raw}}</p>
            <p><span class="font-bold">Min - Max:</span>  {{game.minPlayers}} - {{game.maxPlayers}} joueurs</p>
            <p><span class="font-bold">Âge:</span> {{game.minAge}} ans et +</p>
            <p><span class="font-bold">Temps de jeux:</span> {{game.playingTime}} minutes</p>
            <p><span class="font-bold">Temps minimum:</span> {{game.minPlayTime}} minutes</p>
            <p><span class="font-bold">Temps maximum:</span> {{game.maxPlayTime}} minutes</p>
        </div>
        <div class="w-full flex justify-end">
            {{ include('components/btn/ancre.html.twig', {'text': 'Créer un évènement', 'path': path('event_new', {'id': game.id})}) }}
        </div>
    </div>
</div>
{% endblock %}

templates/game/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello GameController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>C:/laragon/www/gamefinder/src/Controller/GameController.php</code></li>
        <li>Your template at <code>C:/laragon/www/gamefinder/templates/game/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

templates/game/showGames.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste de jeux{% endblock %}

{% block body %}
<div class="flex flex-col gap-10 w-full h-dvh md:p-7">

    <h2 class="flex gap-2 font-bold">
        Jeux
        <svg width="54" height="54" viewBox="0 0 54 54" fill="none" xmlns="http://www.w3.org/2000/svg">
            <g filter="url(#filter0_d_5_66)">
                <rect x="15" y="15" width="24" height="24" rx="4" fill="url(#paint0_linear_5_66)" />
                <path
                    d="M19.7272 22.7654C21.2335 22.7654 22.4545 21.5443 22.4545 20.0381C22.4545 18.5319 21.2335 17.3108 19.7272 17.3108C18.221 17.3108 17 18.5319 17 20.0381C17 21.5443 18.221 22.7654 19.7272 22.7654Z"
                    fill="#FAECFF" />
                <path
                    d="M19.7272 37.3108C21.2335 37.3108 22.4545 36.0898 22.4545 34.5836C22.4545 33.0773 21.2335 31.8563 19.7272 31.8563C18.221 31.8563 17 33.0773 17 34.5836C17 36.0898 18.221 37.3108 19.7272 37.3108Z"
                    fill="#FAECFF" />
                <path
                    d="M26.9999 30.0381C28.5062 30.0381 29.7272 28.8171 29.7272 27.3109C29.7272 25.8046 28.5062 24.5836 26.9999 24.5836C25.4937 24.5836 24.2727 25.8046 24.2727 27.3109C24.2727 28.8171 25.4937 30.0381 26.9999 30.0381Z"
                    fill="#FAECFF" />
                <path
                    d="M34.2728 22.7654C35.779 22.7654 37 21.5443 37 20.0381C37 18.5319 35.779 17.3108 34.2728 17.3108C32.7666 17.3108 31.5455 18.5319 31.5455 20.0381C31.5455 21.5443 32.7666 22.7654 34.2728 22.7654Z"
                    fill="#FAECFF" />
                <path
                    d="M34.2728 37.3108C35.779 37.3108 37 36.0898 37 34.5836C37 33.0773 35.779 31.8563 34.2728 31.8563C32.7666 31.8563 31.5455 33.0773 31.5455 34.5836C31.5455 36.0898 32.7666 37.3108 34.2728 37.3108Z"
                    fill="#FAECFF" />
            </g>
            <defs>
                <filter id="filter0_d_5_66" x="0" y="0" width="54" height="54" filterUnits="userSpaceOnUse"
                    color-interpolation-filters="sRGB">
                    <feFlood flood-opacity="0" result="BackgroundImageFix" />
                    <feColorMatrix in="SourceAlpha" type="matrix"
                        values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha" />
                    <feOffset />
                    <feGaussianBlur stdDeviation="7.5" />
                    <feComposite in2="hardAlpha" operator="out" />
                    <feColorMatrix type="matrix"
                        values="0 0 0 0 0.867352 0 0 0 0 0.4875 0 0 0 0 1 0 0 0 0.5 0" />
                    <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_5_66" />
                    <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_5_66" result="shape" />
                </filter>
                <linearGradient id="paint0_linear_5_66" x1="17.3001" y1="46.2" x2="49.2578" y2="41.422"
                    gradientUnits="userSpaceOnUse">
                    <stop stop-color="#D86AFF" />
                    <stop offset="1" stop-color="#BD00FF" />
                </linearGradient>
            </defs>
        </svg>
    </h2>
    <div id="games" class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-5  gap-4 justify-center items-center">
        {% for game in games %}
            {{ include('components/game/card.html.twig', {'game': game, 'path': ''}) }}
        {% endfor %}
    </div>
</div>
{% endblock %}